version: '3.8'

services:
  # Laravel PHP service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - "9000:9000"
    volumes:
    
      - ./database/migrations:/var/www/database/migrations

    networks:
      - laravel_network
    depends_on:
      - db
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=root
      
  # MySQL service
  db:
    image: mysql:5.7
    container_name: laravel_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
    ports:
      - "33061:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel_network

  # Nginx service (optional but common for Laravel setups)
  nginx:
    image: nginx:latest
    container_name: laravel_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./public:/var/www/public # Mount Laravel's public folder

    ports:
      - "8080:80"
    networks:
      - laravel_network
    depends_on:
      - app

  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - "8098:8080" # Adminer will be accessible on localhost:8081
    networks:
      - laravel_network
    depends_on:
      - db


# Volumes
volumes:
  db_data:

# Networks
networks:
  laravel_network:
    driver: bridge
